[profile.default]
src = "contracts"
test = "test"
script = "script"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]
